model_provider = "fox"
model = "gpt-5"
model_reasoning_effort = "high"
disable_response_storage = true


[model_providers.fox]
name = "fox"
base_url = "替换为您的URL"
wire_api = "responses"
requires_openai_auth = true